In [5]:
from latentis.project import RelativeProjector
from latentis.project import relative
from latentis.space import LatentSpace
from latentis.sample import Uniform

import torch

In [6]:
space = LatentSpace(name="x", vectors=torch.randn(5, 10))
anchors = space.sample(sampler=Uniform(), n=3)
space.shape, anchors.shape

(torch.Size([5, 10]), torch.Size([3, 10]))

In [7]:
projector = RelativeProjector(
    projection_fn=relative.cosine_proj,
)

projector(x=space, anchors=anchors).vectors

tensor([[ 0.2935,  0.0381,  1.0000],
        [-0.0064,  1.0000,  0.0381],
        [ 0.0294, -0.6105,  0.5409],
        [ 1.0000, -0.0064,  0.2935],
        [-0.1089, -0.0395, -0.2962]])

In [8]:
rel_space = space.to_relative(anchors=anchors, projector=projector)
rel_space, rel_space.vectors

(RelativeSpace(name=x/relative_cosine_proj, vectors=torch.Size([5, 3]), features=dict_keys([])),
 tensor([[ 0.2935,  0.0381,  1.0000],
         [-0.0064,  1.0000,  0.0381],
         [ 0.0294, -0.6105,  0.5409],
         [ 1.0000, -0.0064,  0.2935],
         [-0.1089, -0.0395, -0.2962]]))

In [9]:
relative.cosine_proj(
    x=space.vectors,
    anchors=rel_space.anchors.vectors,
)

tensor([[ 0.2935,  0.0381,  1.0000],
        [-0.0064,  1.0000,  0.0381],
        [ 0.0294, -0.6105,  0.5409],
        [ 1.0000, -0.0064,  0.2935],
        [-0.1089, -0.0395, -0.2962]])