In [ ]:
!pip install latentis
!pip install backports.strenum # I forgot to add this to the dependencies of the package

In [ ]:
from latentis.relative.projection import Projections
from latentis.relative.projection import RelativeProjector
from latentis.transforms import Transforms

import torch

In [ ]:
x = torch.randn(5, 10)
anchors = x[:3]

In [ ]:
RelativeProjector(
    projection=Projections.COSINE,
    anchors=anchors,
    abs_transforms=Transforms.StandardScaling(),
    rel_transforms=None
)(x=x)

tensor([[ 1.0000, -0.6172, -0.3320],
        [-0.6172,  1.0000, -0.5372],
        [-0.3320, -0.5372,  1.0000],
        [-0.1798,  0.3990, -0.2856],
        [ 0.0536, -0.2391,  0.2292]])

In [ ]:
RelativeProjector(
    projection=Projections.COSINE,
    abs_transforms=Transforms.StandardScaling(),
    rel_transforms=None
)(x=x, anchors=anchors)

tensor([[ 1.0000, -0.6172, -0.3320],
        [-0.6172,  1.0000, -0.5372],
        [-0.3320, -0.5372,  1.0000],
        [-0.1798,  0.3990, -0.2856],
        [ 0.0536, -0.2391,  0.2292]])

In [ ]:
projector = RelativeProjector(
    anchors=anchors,
    projection=Projections.COSINE,
    abs_transforms=Transforms.StandardScaling(),
    rel_transforms=Transforms.L2()
)
projector(x=x)

tensor([[ 0.8189, -0.5054, -0.2719],
        [-0.4777,  0.7739, -0.4158],
        [-0.2807, -0.4542,  0.8455],
        [-0.3440,  0.7635, -0.5465],
        [ 0.1597, -0.7126,  0.6831]])